import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
 src: './fonts/GeistVF.woff',
 variable: '--font-geist-sans',
 weight: '100 900',
});
const geistMono = localFont({
 src: './fonts/GeistMonoVF.woff',
 variable: '--font-geist-mono',
 weight: '100 900',
});

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang='en'>
   <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <div className='p-4'>
     <header className='outline outline-1 outline-red-500 p-3'>
      <h1>globale layout that wraps everything</h1>
     </header>
     {children}
    </div>
   </body>
  </html>
 );
}
